"""עמודת "מזהה פריט" — the automatic item identifier.

Covers the spec's rules: an 11-digit number generated by the system, unique
inside its board, issued to existing items when the column is added and to
every item and sub-item created afterwards, never reused after a delete, and
re-issued when an item ends up on a different board. The copy behaviour
(number vs. link) is a column setting.
"""


def _board_with_id_col(client, admin_id, name="מזהה פריט"):
    bid = client.post("/api/boards", json={"name": name, "user_id": admin_id}).json()["id"]
    r = client.patch(f"/api/boards/{bid}",
                     json={"columns": [{"type": "item_id", "title": "מזהה פריט"}], "user_id": admin_id})
    assert r.status_code == 200, r.text
    return bid, r.json()["columns"][0]["id"]


def _items(client, bid, admin_id):
    return client.get(f"/api/boards/{bid}?user_id={admin_id}").json()["tasks"]


def _uids(items):
    out = []
    for t in items:
        out.append(t["item_uid"])
        out += [s["item_uid"] for s in t.get("subtasks", [])]
    return out


def test_existing_items_get_an_id_when_the_column_is_added(client, admin_id):
    """1 — adding the column to a board that already holds items."""
    bid, _ = _board_with_id_col(client, admin_id)
    uids = _uids(_items(client, bid, admin_id))
    assert uids and all(u and u.isdigit() and len(u) == 11 for u in uids), uids
    assert len(set(uids)) == len(uids)          # unique inside the board


def test_sub_items_follow_the_same_id_logic(client, admin_id):
    """Section 8 — sub-items get an automatic, unique, plain numeric id by the
    same logic as items: no prefix, no sub-item-specific format, and the ones
    that predate the column are covered by the backfill too."""
    bid = client.post("/api/boards", json={"name": "תתי-פריטים", "user_id": admin_id}).json()["id"]
    parent = client.get(f"/api/boards/{bid}?user_id={admin_id}").json()["tasks"][0]
    # a sub-item created BEFORE the column exists
    early = client.post("/api/tasks", json={"parent_id": parent["id"], "title": "תת מוקדם",
                                            "user_id": admin_id}).json()
    client.patch(f"/api/boards/{bid}",
                 json={"columns": [{"type": "item_id", "title": "מזהה פריט"}], "user_id": admin_id})
    # and one created after
    client.post("/api/tasks", json={"parent_id": parent["id"], "title": "תת מאוחר", "user_id": admin_id})

    items = _items(client, bid, admin_id)
    subs = [s for t in items for s in t.get("subtasks", [])]
    assert len(subs) == 2
    for s in subs:
        uid = s["item_uid"]
        assert uid and uid.isdigit() and len(uid) == 11, uid   # plain 11 digits, no prefix
    # unique against each other and against every item on the board
    everything = _uids(items)
    assert len(set(everything)) == len(everything)
    assert next(s for s in subs if s["id"] == early["id"])["item_uid"]


def test_new_item_and_sub_item_get_their_own_id(client, admin_id):
    """2 + section 8 — an item created after the column, and its sub-item."""
    bid, _ = _board_with_id_col(client, admin_id)
    before = set(_uids(_items(client, bid, admin_id)))
    item = client.post("/api/tasks", json={"board_id": bid, "title": "חדש", "user_id": admin_id}).json()
    sub = client.post("/api/tasks", json={"parent_id": item["id"], "title": "תת", "user_id": admin_id}).json()
    for t in (item, sub):
        assert t["item_uid"] and t["item_uid"].isdigit() and len(t["item_uid"]) == 11
    assert item["item_uid"] != sub["item_uid"]
    assert not before & {item["item_uid"], sub["item_uid"]}


def test_a_recreated_item_never_reuses_the_deleted_one_s_id(client, admin_id):
    """7 — delete an item, create another with the same name → a new id."""
    bid, _ = _board_with_id_col(client, admin_id)
    first = client.post("/api/tasks", json={"board_id": bid, "title": "אותו שם", "user_id": admin_id}).json()
    client.delete(f"/api/tasks/{first['id']}")
    second = client.post("/api/tasks", json={"board_id": bid, "title": "אותו שם", "user_id": admin_id}).json()
    assert second["item_uid"] != first["item_uid"]


def test_an_item_moved_to_another_board_and_back_gets_a_new_id(client, admin_id):
    """5 + section 9 — move the item to another board and bring it back: it does
    not keep its original identifier, and it does not get it back on return."""
    home, _ = _board_with_id_col(client, admin_id, "בית")
    away, _ = _board_with_id_col(client, admin_id, "אחר")
    item = client.post("/api/tasks", json={"board_id": home, "title": "נודד", "user_id": admin_id}).json()
    sub = client.post("/api/tasks", json={"parent_id": item["id"], "title": "תת נודד",
                                          "user_id": admin_id}).json()
    original, original_sub = item["item_uid"], sub["item_uid"]

    def relocate(target):
        r = client.post(f"/api/tasks/{item['id']}/move", json={"board_id": target, "actor_id": admin_id})
        assert r.status_code == 200, r.text
        return next(t for t in _items(client, target, admin_id) if t["id"] == item["id"])

    moved = relocate(away)
    assert moved["item_uid"] != original
    assert moved["subtasks"][0]["item_uid"] != original_sub      # sub-items travel and are re-issued

    back = relocate(home)
    assert back["item_uid"] not in (original, moved["item_uid"])
    assert back["subtasks"][0]["item_uid"] not in (original_sub, moved["subtasks"][0]["item_uid"])
    assert len(back["item_uid"]) == 11 and back["item_uid"].isdigit()


def test_a_sub_item_cannot_be_moved_between_boards_on_its_own(client, admin_id):
    """A sub-item belongs to its parent — it travels with it, never separately."""
    home, _ = _board_with_id_col(client, admin_id, "מקור")
    away, _ = _board_with_id_col(client, admin_id, "יעד")
    item = client.post("/api/tasks", json={"board_id": home, "title": "אב", "user_id": admin_id}).json()
    sub = client.post("/api/tasks", json={"parent_id": item["id"], "title": "בן", "user_id": admin_id}).json()
    r = client.post(f"/api/tasks/{sub['id']}/move", json={"board_id": away, "actor_id": admin_id})
    assert r.status_code == 400


def test_duplicating_the_column_keeps_the_item_s_id(client, admin_id):
    """6 + section 10 — a second id column is a new column, but the identifier
    lives on the item, so both columns show the same number for the same item."""
    bid, col_id = _board_with_id_col(client, admin_id)
    cols = client.get(f"/api/boards/{bid}?user_id={admin_id}").json()["columns"]
    cols.append({"type": "item_id", "title": "מזהה פריט (עותק)"})
    r = client.patch(f"/api/boards/{bid}", json={"columns": cols, "user_id": admin_id})
    assert r.status_code == 200, r.text
    out = r.json()["columns"]
    assert len(out) == 2 and out[0]["id"] != out[1]["id"]
    # the items' identifiers are untouched by adding the second column
    assert all(u and len(u) == 11 for u in _uids(_items(client, bid, admin_id)))


def test_copy_mode_is_stored_on_the_column(client, admin_id):
    """3 + 4 + section 11 — the copy choice is saved at column level, and the
    column defaults to copying the number itself."""
    bid, col_id = _board_with_id_col(client, admin_id)
    cols = client.get(f"/api/boards/{bid}?user_id={admin_id}").json()["columns"]
    assert cols[0]["copy_mode"] == "id"          # default

    cols[0]["copy_mode"] = "url"
    client.patch(f"/api/boards/{bid}", json={"columns": cols, "user_id": admin_id})
    assert client.get(f"/api/boards/{bid}?user_id={admin_id}").json()["columns"][0]["copy_mode"] == "url"

    # anything else falls back to the number
    cols[0]["copy_mode"] = "nonsense"
    client.patch(f"/api/boards/{bid}", json={"columns": cols, "user_id": admin_id})
    assert client.get(f"/api/boards/{bid}?user_id={admin_id}").json()["columns"][0]["copy_mode"] == "id"


def test_the_identifier_cannot_be_set_by_hand(client, admin_id):
    """13 — the value is system-generated; a client cannot dictate it."""
    bid, _ = _board_with_id_col(client, admin_id)
    t = client.post("/api/tasks", json={"board_id": bid, "title": "ניסיון", "user_id": admin_id,
                                        "item_uid": "12345678901"}).json()
    assert t["item_uid"] != "12345678901"
    client.patch(f"/api/tasks/{t['id']}", json={"item_uid": "99999999999", "user_id": admin_id})
    fresh = next(x for x in _items(client, bid, admin_id) if x["id"] == t["id"])
    assert fresh["item_uid"] == t["item_uid"]
